name: Deploy to EC2 and Run Docker

on:
  workflow_run:
    workflows: ["Build and Dockerize"]
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Workflow received completion status from Build and Dockerize."

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: check-status
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: SSH into EC2 Instance and Deploy Docker Image
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/${{ secrets.KEYPAIR_NAME }}.pem
          chmod 600 ~/.ssh/${{ secrets.KEYPAIR_NAME }}.pem
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/${{ secrets.KEYPAIR_NAME }}.pem ubuntu@${{ secrets.EC2_IP }} <<EOF
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ubuntu
            newgrp docker
            DOCKER_COMPOSE_VERSION="2.20.2"
            sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
          EOF

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2



      - name: Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wedseven
          IMAGE_TAG: latest
        run: |
          docker image tag wedseven 637423430820.dkr.ecr.us-east-1.amazonaws.com/wedseven:latest
          docker push 637423430820.dkr.ecr.us-east-1.amazonaws.com/wedseven:latest

          if [ -d "wedseven" ]; then rm -rf wedseven; fi
          git clone https://github.com/Acmf-api/wedseven
          cd wedseven
          docker-compose up -d
